blank_issues_enabled: false
contact_links:
  - name: Twitter
    url: https://twitter.com/DannyDainton
    about: If you have any reporter concerns, that are not functionality issues, feel free to ping me here.
