name: Bug Report
description: Raise an issue with the Reporter
labels: [type: bug, state: needs-triaging]
body:
- type: checkboxes
  attributes:
    label: Is There An Existing Issue
    options:
      - label: I have searched the [issue tracker](https://github.com/DannyDainton/newman-reporter-htmlextra/issues) for similar problems.
        required: true
- type: textarea
  attributes:
    label: What Are You Seeing
    description: A high-level description explaining the issue that you are facing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce The Issue
    description: Provide steps to reproduce the problem.
    placeholder: |
      1. Run Newman using the command in the terminal
      2. Open the new htmlextra report in a browser window
      3. Click on the 'Total Requests' tab
      4. Nothing happens...
- type: markdown
  attributes:
    value: '> **Tip**: You can attach images and recordings to textareas by dragging in the files. More visual examples will help to understand the issue.'
- type: textarea
  attributes:
    label: Full Newman Command Or Node Script
    description: The command used to run the reporter with Newman.
  validations:
    required: true
- type: input
  attributes:
    label: HTMLEXTRA Version
    description: What version of the reporter are you using?
    placeholder: "1.22.5"
  validations:
    required: true
- type: input
  attributes:
    label: Newman Version
    description: What version of Newman are you using?
    placeholder: "5.3.1"
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Context
    description: Any contextual information that might relate to the problem?
