name: Bug Report
description: Raise an issue with the Reporter
labels: [type: bug, state: needs-triaging]
body:
- type: checkboxes
  attributes:
    label: Is There An Existing Issue
    options:
      - label: I have searched the [issue tracker](https://github.com/DannyDainton/newman-reporter-htmlextra/issues) for the same of similar problem.
        required: true
- type: textarea
  attributes:
    label: What Are You Seeing
    description: A high-level description explaining the issue that you are facing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce The Issue
    description: Provide steps to reproduce the problem
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
- type: markdown
  attributes:
    value: '> **Tip**: You can attach images or log files to textareas by clicking to highlight and then dragging files in.'
- type: textarea
  attributes:
    label: Full Newman Command Or Node Script
    description: The command used to run the reporter with Newman.
  validations:
    required: true
- type: input
  attributes:
    label: HTMLEXTRA Version
    description: What version of the reporter are you using?
    placeholder: "1.22.5"
  validations:
    required: true
- type: input
  attributes:
    label: Newman Version
    description: What version of Newman are you using?
    placeholder: "5.3.1"
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Context
    description: Any contextual information that might relate to the problem?
