name: Issue Creation

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey! :wave:\n\nThank you so much for raising the issue, I will review this as soon as I can get to it. :heart:\n\nDanny'
